version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - server/.env
    ports:
      - "5432:5432"  # Expose DB port
    networks:
      - my-network

  backend:
    build: ./server
    container_name: backend
    env_file:
      - server/.env
    ports:
      - "5000:5000" 
    depends_on:
      - db  # Ensure backend starts after DB
    networks:
      - my-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:3000" 
    networks:
      - my-network

volumes:
  pgdata: 

networks:
  my-network:
    driver: bridge
